### ISSUE TITLE
Export to swift using spark fails -> AttributeError: 'SparkContext' object has no attribute 'hadoopConfiguration'

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#28]
The project [SwiftPushWithSpark](https://github.com/snowch/biginsight-examples/tree/master/examples/SwiftPushWithSpark) is failing with:

```
AttributeError: 'SparkContext' object has no attribute 'hadoopConfiguration'
```

The pyspark command is:

```
pyspark --jars "test-1460992369091/SwiftPushWithSpark-all.jar" test-1460992369091/exporttoswift.py '***' '***' '***' 'object_storage_wc' '1460992369091'
```

The jar file contents are:  [SwiftPushWithSpark-all.txt](https://github.com/snowch/biginsight-examples/files/224070/SwiftPushWithSpark-all.txt)

**Comment by gilv** [comment]
@snowch 
it looks like user error, since you setup hadoopConfiguration in your code and it fails. It's not related the Swift driver, but general Spark usage. Otherwise you were seeing some Swift  / Stocator related errors.

I can gladly assist you if i will see the code where you setup hadoopConfiguration.
Can you share with me those lines where you setup hadoopConfiguration?

**Comment by snowch** [comment]
This is required from python:

```
sc._jsc.hadoopConfiguration().set('my.mapreduce.setting', 'someVal')
```

**Comment by gilv** [comment]
@snowch you closed it, because it works for you?

If it helps you this is how i am using it with python  (to access SL object store )

import pprint
import os
from pyspark.sql import SQLContext
from pyspark import SparkContext, SparkConf
from pyspark.sql.types import *

conf = SparkConf().setAppName("TEST")

sc = SparkContext(conf=conf)

sc._jsc.hadoopConfiguration().set("fs.swift2d.impl","com.ibm.stocator.fs.ObjectStoreFileSystem")
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".auth.url",authurl)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".public","true")
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".tenant",tenant)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".password",apikey)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".username",username)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".auth.method","swiftauth")

sqlContext = SQLContext(sc)

......
