### ISSUE TITLE
gradlew RunSquirrel - on windows (cygwin) - $'\r': command not found

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#79]
```
$ ../gradlew RunSquirrel
../gradlew: line 2: $'\r': command not found
../gradlew: line 8: $'\r': command not found
../gradlew: line 11: $'\r': command not found
../gradlew: line 14: $'\r': command not found
../gradlew: line 17: $'\r': command not found
../gradlew: line 18: syntax error near unexpected token `$'{\r''
'./gradlew: line 18: `warn ( ) {
```

**Comment by cyborg7** [comment]
I think we got this above output because we ran it without absolute path. Also the dir name was incorrect. It should be SquirrelSQL instead of RunSquirrel.

I made another attempt which resulted in another error as below.

---

## Output

Rohan Vaidyanathan@ADMINIB-UDH05BT /cygdrive/c/Big_Data/BigInsights/GitSamples/biginsight-examples
$ ./gradlew.bat -p examples/SquirrelSQL
Defining custom 'clean' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0

FAILURE: Build failed with an exception.
- Where:
  Build file 'C:\Big_Data\BigInsights\GitSamples\biginsight-examples\examples\SquirrelSQL\build.gradle' line: 27
- What went wrong:
  A problem occurred evaluating root project 'SquirrelSQL'.
  
  > Cannot invoke method getAt() on null object
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.191 secs

Rohan Vaidyanathan@ADMINIB-UDH05BT /cygdrive/c/Big_Data/BigInsights/GitSamples/biginsight-examples

**Comment by snowch** [comment]
On cygwin, ./gradlew.bat should be used and not ./gradlew.

**Comment by snowch** [comment]
I've added this to a FAQ so closing this issue.
